### ISSUE TITLE
RGB20: introduce dedicated type for decimal precision

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rust-rgb20#1]

**Comment by josediegorobles** [comment]
Hi, there are some ghideline about this issue?

**Comment by dr-orlovsky** [comment]
It should be a wrapper type around `amplify::num::u5`, but it also should control that the value is never getting above 18 (since 5-bit may allow range `0..=23` and we need `0..=18`). The type should be `Deref` into `u8` and should have `TryFrom` convertors for `u5`, `u8`, `usize` that check that boundary.

**Comment by dr-orlovsky** [comment]
Well, you can make it a wrapper not around `u5` but normal `u8` since you have to control the range anyway...

**Comment by josediegorobles** [comment]
Ok, I will give a try this week

**Comment by josediegorobles** [comment]
Hi, i can't build the project, I send the compiler error in a file.
[errror_rgb_core.txt](https://github.com/rgb-org/rgb-core/files/6952230/errror_rgb_core.txt)

**Comment by dr-orlovsky** [comment]
Completed in https://github.com/RGB-WG/rgb-wallet/
