### ISSUE TITLE
Support OpretFirst in create_rgb20

### ISSUE THREAD

**Issue by cryptoquick** [RGB-WG/rust-rgb20#6]
When creating a contract genesis, the OwnedRights defaults to a TapretFirst revealed seal. See here:
https://github.com/BP-WG/bp-core/blob/c3ce5268c09afe823b1ca2ee3ef5f56cec483b4c/seals/src/txout/blind.rs#L91

When calling `into_seal_value_map` within `create_rgb20`, the above from method is called and there seems to be no way to override this behavior:
https://github.com/RGB-WG/rust-rgb20/blob/7599f0faa0397b89750b820920a0ec82079bea15/src/create.rs#L72

I believe this causes complications further down the line when attempting to transfer; I'm trying to debug why I get a different derived scriptpubkey hash when trying to construct a PSBT to transfer the token.

**Comment by dr-orlovsky** [comment]
So you basically need a way of supporting OpretFirst in RGB20 asset creation, which would require a bit of refactoring in the RGB standard library... Ok, will address that
