### ISSUE TITLE
`outpoint_coins` is unreliable at discovering coins on an outpoint

### ISSUE THREAD

**Issue by cryptoquick** [RGB-WG/rust-rgb20#8]
This is a strange one, and I can't tell if the issue is on the RGB or BitMask side. Take a look at this very ugly PR to get a sense for what I'm struggling with:
https://github.com/diba-io/bitmask-core/pull/85

Occasionally, I'd say maybe 50/50 on average, a newly created contract will fail to discover coins minted to an outpoint. I suspect this might have something to do with the ordering of the outputs we're making, maybe, since that's not quite deterministic, but it's been hard for me to pin this one down.

**Comment by dr-orlovsky** [comment]
Not relevant with the move to interfaces in https://github.com/RGB-WG/rgb-wallet/ v0.10
